### ISSUE TITLE
Add Uploaded and Compressed File Info

### ISSUE THREAD

**Issue by iwtga** [githubcrce/Image-Compressor#2]
Adding info about the uploaded and compressed image info would be a good enhancement, giving the user an idea about the size of compressed image before needing to download it.

**Comment by warrenferns** [comment]
Also user defined parameters need to be added such as Scale and Quality

**Comment by daptheHuman** [comment]
> Adding info about the uploaded and compressed image info would be a good enhancement, giving the user an idea about the size of compressed image before needing to download it.

#3 
I'm adding the file size info and the percentage before and after the compression took the size

**Comment by iwtga** [comment]
Thanks @daptheHuman :)
